### ISSUE TITLE
Hydrogram does not recognize the updateBotChatBoost constructor (904dd49c) introduced in layer 166

### ISSUE THREAD

**Issue by KSKOP69** [hydrogram/hydrogram#9]
### Checklist

- [X] I am sure the error is coming from Hydrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/hydrogram/hydrogram/archive/dev.zip` and reproduced the issue using the latest development version

### Description

mtproto issue 

### Steps to reproduce

1. Installed hydrogram and py-tgcalls , ntgcalls.
2. made simple codes to test.
3. deployed the bot.
4. got the error

### Logs

```shell
[10-Dec-23 13:28:28 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-1072978' coro=<Session.handle_packet() done, defined at /opt/venv/lib/python3.11/site-packages/hydrogram/session/session.py:195> exception=ValueError('The server sent an unknown constructor: 0x904dd49c\n87a77bb2 5c088b36 45986150 e6860c15 7e6d449f f092ece6')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/crypto/mtproto.py", line 69, in unpack
    message = Message.read(data)
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/message.py", line 47, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/msg_container.py", line 41, in read
    return MsgContainer([Message.read(data) for _ in range(count)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/msg_container.py", line 41, in <listcomp>
    return MsgContainer([Message.read(data) for _ in range(count)])
                         ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/message.py", line 47, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/gzip_packed.py", line 42, in read
    return cast(GzipPacked, TLObject.read(BytesIO(decompress(Bytes.read(data)))))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/types/updates_t.py", line 180, in read
    updates = TLObject.read(b)
              ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/primitives/vector.py", line 48, in read
    return List(t.read(data) if t else Vector.read_bare(data, size) for _ in range(count))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/primitives/vector.py", line 48, in <genexpr>
    return List(t.read(data) if t else Vector.read_bare(data, size) for _ in range(count))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/primitives/vector.py", line 39, in read_bare
    return Long.read(b) if size == 8 else TLObject.read(b)
                                          ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
                          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 2421019804

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/session/session.py", line 196, in handle_packet
    data = await self.loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/hydrogram/crypto/mtproto.py", line 80, in unpack
    raise ValueError(
ValueError: The server sent an unknown constructor: 0x904dd49c
87a77bb2 5c088b36 45986150 e6860c15 7e6d449f f092ece6
```

**Comment by eyMarv** [comment]
I think this is cause needs layer update

**Comment by alissonlauffer** [comment]
Hey, can you try installing the `feat/layer-167` branch and check if this issue persists?

To install, just run:
```shell
pip3 install -U https://github.com/hydrogram/hydrogram/archive/feat/layer-167.zip
```

Thanks!
